-- Create the projects table
create table public.projects (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  category text not null,
  title text not null,
  image text not null,
  description text not null,
  link text
);

-- Enable Row Level Security (RLS)
alter table public.projects enable row level security;

-- Create a policy that allows anyone to read the projects table
create policy "Enable read access for all users"
on public.projects
for select
to public
using (true);

-- Insert initial data (from Gallery.tsx)
insert into public.projects (category, title, image, description)
values
  (
    'Fashion Brand',
    'Koleksi Kaos Kami',
    'https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    'Desain streetwear original dengan tema urban & tipografi.'
  ),
  (
    'Community & Content',
    'Meme & Engagement',
    'https://images.unsplash.com/photo-1611162617474-5b21e879e113?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    'Konten viral yang membangun interaksi komunitas organik.'
  ),
  (
    'Web Development',
    'Modern Web Apps',
    'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    'Pengembangan website responsif dengan React & Tailwind.'
  );
