-- Create the testimonials table
create table public.testimonials (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  role text not null,
  content text not null,
  rating integer default 5,
  avatar_url text
);

-- Enable Row Level Security (RLS)
alter table public.testimonials enable row level security;

-- Policy: Allow anyone to read testimonials
create policy "Allow public to view testimonials"
on public.testimonials
for select
to public
using (true);

-- Policy: Allow only authenticated users (admin) to insert/update/delete
create policy "Allow authenticated to manage testimonials"
on public.testimonials
for all
to authenticated
using (true)
with check (true);

-- Insert initial data
insert into public.testimonials (name, role, content, rating)
values
  (
    'Pelanggan Kaos Kami',
    'Verified Buyer',
    'Desainnya relate banget sama anak muda jaman now. Bahannya juga adem dipakai nongkrong. Ditunggu koleksi barunya!',
    5
  ),
  (
    'Member Komunitas',
    'Top Contributor',
    'Grup "Kami Depresi dan Bahagia" bener-bener jadi tempat safe space. Adminnya (Hengki) tegas tapi asik banget cara manage membernya.',
    5
  ),
  (
    'Rekan Mahasiswa',
    'Bisnis Digital UNM',
    'Hengki punya visi bisnis yang tajam. Gabungan skill coding sama marketingnya bikin dia beda dari mahasiswa lain.',
    5
  );
