-- Create the subscribers table
create table public.subscribers (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  email text not null unique
);

-- Enable Row Level Security (RLS)
alter table public.subscribers enable row level security;

-- Policy: Allow anyone to insert (subscribe)
create policy "Allow public to subscribe"
on public.subscribers
for insert
to public
with check (true);

-- Policy: Allow only authenticated users (admin) to view subscribers
create policy "Allow authenticated to view subscribers"
on public.subscribers
for select
to authenticated
using (true);
