-- Create the messages table
create table public.messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  message text not null
);

-- Enable Row Level Security (RLS)
alter table public.messages enable row level security;

-- Policy: Allow anyone (anon) to insert messages
create policy "Allow anon to insert messages"
on public.messages
for insert
to anon
with check (true);

-- Policy: Allow only authenticated users (service_role/admin) to view messages
create policy "Allow authenticated to view messages"
on public.messages
for select
to authenticated
using (true);
